[versions]
hiltVersion = "2.48"
coreVersion = "1.12.0"
lifecycleVersion = "2.6.2"
activityVersion = "1.8.1"
composeBomVersion = "2023.10.01"
buildGradle = "8.1.4"
androidLibrary = "8.1.4"
arturboshDetekt = "1.23.0"
devTools = "1.8.10-1.0.9"
daggerHilt = "2.44.1"
hiltComposeVersion = "1.1.0"
jetbrainsKotlin = "1.8.10"
androidApplication = "8.1.2"
gsonGson = "2.10.1"
jUnit = "4.13.2"
navVersion = "2.7.5"
testJunit = "1.1.5"
espressoCore = "3.5.1"

[libraries]
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-nav-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltComposeVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityVersion" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
nav-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonGson" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
junit = { module = "junit:junit", version.ref = "jUnit" }
junit-test = { module = "androidx.test.ext:junit", version.ref = "testJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "buildGradle" }


[plugins]
application-android = { id = "com.android.application", version.ref = "androidApplication" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlin" }
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "arturboshDetekt" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devTools" }
library-android = { id = "com.android.library", version.ref = "androidLibrary" }
